@startjson

#highlight "properties"/"spdxId"  
#highlight "properties"/"spdxId"/"type"  
#highlight "properties"/"spdxId"/"format"  
#highlight "properties"/"creationInfo"
#highlight "properties"/"creationInfo"/"$ref"

!include ../SoftwareArtifact.json
@endjson
